@echo off
cd /d %~dp0
echo [1/3] Creating venv...
python -m venv backend\.venv
echo [2/3] Installing backend deps...
backend\.venv\Scripts\pip install -r backend\requirements.txt
echo [3/3] Starting backend on http://0.0.0.0:8000 ...
backend\.venv\Scripts\uvicorn main:app --host 0.0.0.0 --port 8000 --reload
